startindex=max(find(t <= starttime));
stopindex=min(find(t >= stoptime));

time=t(startindex:stopindex);
settlerx=settler(startindex:stopindex,:);

figure(16);
subplot(3,3,1);
plot(time,settlerx(:,33));
grid on;
title('TSS, layer 2');
subplot(3,3,2);
plot(time,settlerx(:,34));
grid on;
title('TSS, layer 3');
subplot(3,3,3);
plot(time,settlerx(:,35));
grid on;
title('TSS, layer 4');
subplot(3,3,4);
plot(time,settlerx(:,36));
grid on;
title('TSS, layer 5');
subplot(3,3,5);
plot(time,settlerx(:,37));
grid on;
title('TSS, layer 6');
subplot(3,3,6);
plot(time,settlerx(:,38));
grid on;
title('TSS, layer 7');
subplot(3,3,7);
plot(time,settlerx(:,39));
grid on;
title('TSS, layer 8');
subplot(3,3,8);
plot(time,settlerx(:,40));
grid on;
title('TSS, layer 9');
subplot(3,3,9);
plot(time,settlerx(:,41));
grid on;
title('TSS, layer 10');
